name: Daily Goal Keeper

on:
  schedule:
    - cron: '0 20 * * 0-4' # Asia/Seoul(UTC+9)
  workflow_dispatch:

jobs:
  sendMessage:
    runs-on: ubuntu-24.04

    steps:
      - name: Send Message to Discord Channel!
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"하루 목표를 작성하여 오후 1시까지 공유해 주세요!\"}" \
          ${{ secrets.DAILY_DISCORD_WEBHOOK_URL }}

