name: Weekly Goal Keeper

on:
  schedule:
    - cron: '0 1 * * 0' # Asia/Seoul(UTC+9)
  workflow_dispatch:

jobs:
  sendMessage:
    runs-on: ubuntu-24.04

    steps:
      - name: Send Message to Discord Channel!
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d "{\"content\": \"주간 목표를 꼼꼼히 작성하여 공유해 주세요! 월요일까지 작성해주시면 됩니다 :)\"}" \
          ${{ secrets.WEEKLY_DISCORD_WEBHOOK_URL }}

